### ISSUE TITLE
Clarify the shades/icons 

### ISSUE THREAD

**Issue by twalton83** [mutoo/critterpedia-plus#2]
At first, the graph was a bit hard to understand, because in this screenshot, you can see three different shades of grey, but the chart legend denotes two different color greys, a dark shade and a light shade. It appears that the "medium" shade (which is called the "light shade in the legend" is for critters in season in the other hemisphere, and the actual visually lightest shade is for critters unavailable in both hemispheres at this moment, but the legend doesn't reflect that. 

I know the default butterfly is intended to denote that the critter is unavailable at this time in both hemispheres, but perhaps it could be clearer and added to the chart legend. I understand the insect icons that pop up are based on availability, but when you're looking for shades of grey, the greyed out butterfly icons can be a bit distracting from other grey icons. 

<img width="209" alt="Screen Shot 2020-06-12 at 1 13 37 PM" src="https://user-images.githubusercontent.com/22967723/84542784-0288de80-acaf-11ea-848e-5f0bd9c749c6.png">
<img width="607" alt="Screen Shot 2020-06-12 at 1 14 53 PM" src="https://user-images.githubusercontent.com/22967723/84542808-0c124680-acaf-11ea-90a0-a216dfb9548c.png">

 I think it might be more helpful, visually, to maybe have a slight overlay on the colorized version of the critter icons instead of the Dark Shade when a critter isn't available at a specific time, but is in season in your hemisphere. To me, a user, in a comparison chart like this, a dark color grey more so denotes total unavailability (which is what the default butterfly icon is supposed to do).

EDIT: I'm embarrassed- I realized this is pretty much the same color scheme as the in game encyclopedia. Welp, I'll close this!

**Comment by mutoo** [comment]
@twalton83 thanks you for your feedback anyway. I do find it very difficult to express the availability in such a small grid. I had tried opacity, shade, and eventually, I find it easier to combine these two. 

The default butterfly icon sometimes makes me confused as well.
