### ISSUE TITLE
adding sea creatures

### ISSUE THREAD

**Issue by simonstey** [mutoo/critterpedia-plus#3]
Hi!

since sea creatures were introduced recently, I was wondering whether you could add a dedicated tab for them in citterpedia+ too?

thanks a lot and keep up the good work!

**Comment by simonstey** [comment]
sea creatures data can be found e.g. here https://github.com/alexislours/ACNHAPI/blob/master/sea.json

**Comment by mutoo** [comment]
Hi @simonstey, thanks for your update. Yeah sure, I'll add the sea creature tab soon, before adding the sea creature data, I'd like to draw some icons first.

**Comment by mutoo** [comment]
@simonstey the sea creatures tab is available on https://critterpedia-plus.mutoo.im/#/discovery/sea-creatures now :D
